---
- name: collect host facts
  hosts: "{{ _hosts }}"
  vars:
    facts_aws_region: us-east-2
    facts_aws_bucket_prefix: "{{ lookup('ansible.builtin.env', 'AWS_ACCESS_KEY_ID')[1:5] | lower }}"
    facts_aws_bucket_name: "{{ reports_aws_bucket_prefix }}-facts"

  tasks:
    - name: store facts
      set_fact:
        facts_dump: "{{ ansible_facts }}"

    - name: get current user
      command: whoami
      register: current_user

    - name: set custom fact
      set_fact:
        facts_dump: "{{ facts_dump | combine( { 'custom_fact': current_user } )}}"

    - name: Create report bucket
      amazon.aws.s3_bucket:
        name: "{{ facts_aws_bucket_name }}"
        region: "{{ facts_aws_region }}"
        state: present
        object_ownership: BucketOwnerPreferred
      delegate_to: localhost
      run_once: true

    - name: Put facts
      amazon.aws.s3_object:
        bucket: "{{ facts_aws_bucket_name }}"
        object: "{{ inventory_hostname }}/{{ ansible_facts.date_time.iso8601 }}.json"
        content: "{{ facts_dump | to_nice_json}}"
        mode: put
      delegate_to: localhost
